load("@gazelle//:def.bzl", "gazelle")
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")
load("@rules_license//rules:license.bzl", "license")
load("@rules_pkg//:pkg.bzl", "pkg_zip")

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

license(
    name = "license",
    license_kinds = [
        "@rules_license//licenses/spdx:Apache-2.0",
    ],
    license_text = "LICENSE",
)

# gazelle:prefix github.com/GoogleCloudPlatform/proto-gen-md-diagrams
# gazelle:exclude test/protos/**
gazelle(name = "gazelle")

go_library(
    name = "main_lib",
    srcs = ["main.go"],
    importpath = "github.com/GoogleCloudPlatform/proto-gen-md-diagrams",
    visibility = ["//visibility:private"],
    deps = ["//pkg/proto"],
)

go_binary(
    name = "main",
    basename = "proto-gen-md-diagrams",
    embed = [":main_lib"],
    visibility = ["//visibility:public"],
)

# Cross-compiled binaries for supported release platforms
go_binary(
    name = "main_linux_amd64",
    basename = "proto-gen-md-diagrams",
    embed = [":main_lib"],
    goarch = "amd64",
    goos = "linux",
    visibility = ["//visibility:public"],
)

go_binary(
    name = "main_darwin_amd64",
    basename = "proto-gen-md-diagrams",
    embed = [":main_lib"],
    goarch = "amd64",
    goos = "darwin",
    visibility = ["//visibility:public"],
)

go_binary(
    name = "main_darwin_arm64",
    basename = "proto-gen-md-diagrams",
    embed = [":main_lib"],
    goarch = "arm64",
    goos = "darwin",
    visibility = ["//visibility:public"],
)

go_binary(
    name = "main_windows_amd64",
    basename = "proto-gen-md-diagrams",
    embed = [":main_lib"],
    goarch = "amd64",
    goos = "windows",
    visibility = ["//visibility:public"],
)

# Release zip archives for each platform
pkg_zip(
    name = "main_linux_amd64_zip",
    srcs = [
        "LICENSE",
        "NOTICE",
        "README.md",
        ":main_linux_amd64",
    ],
    out = "dist/proto-gen-md-diagrams-linux-x86_64.zip",
    visibility = ["//visibility:public"],
)

pkg_zip(
    name = "main_darwin_amd64_zip",
    srcs = [
        "LICENSE",
        "NOTICE",
        "README.md",
        ":main_darwin_amd64",
    ],
    out = "dist/proto-gen-md-diagrams-osx-x86_64.zip",
    visibility = ["//visibility:public"],
)

pkg_zip(
    name = "main_darwin_arm64_zip",
    srcs = [
        "LICENSE",
        "NOTICE",
        "README.md",
        ":main_darwin_arm64",
    ],
    out = "dist/proto-gen-md-diagrams-osx-arm64.zip",
    visibility = ["//visibility:public"],
)

pkg_zip(
    name = "main_windows_amd64_zip",
    srcs = [
        "LICENSE",
        "NOTICE",
        "README.md",
        ":main_windows_amd64",
    ],
    out = "dist/proto-gen-md-diagrams-win-x86_64.zip",
    visibility = ["//visibility:public"],
)

filegroup(
    name = "release_zips",
    srcs = [
        ":main_darwin_amd64_zip",
        ":main_darwin_arm64_zip",
        ":main_linux_amd64_zip",
        ":main_windows_amd64_zip",
    ],
    visibility = ["//visibility:public"],
)

archive_base_name = "proto-gen-md-diagrams"

pkg_zip(
    name = "main_zip",
    srcs = [
        "LICENSE",
        "NOTICE",
        "README.md",
        ":main",
    ],
    out = "dist/archive.zip",
    package_file_name = select({
        "on_linux": "{}-linux-x86_64.zip".format(archive_base_name),
        "on_osx_x64": "{}-osx-x86_64.zip".format(archive_base_name),
        "on_windows": "{}-win-x86_64.zip".format(archive_base_name),
        "on_osx_arm64": "{}-osx-arm64.zip".format(archive_base_name),
    }),
)

config_setting(
    name = "on_linux",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
)

config_setting(
    name = "on_windows",
    constraint_values = [
        "@platforms//os:windows",
        "@platforms//cpu:x86_64",
    ],
)

config_setting(
    name = "on_osx_x64",
    constraint_values = [
        "@platforms//os:osx",
        "@platforms//cpu:x86_64",
    ],
)

config_setting(
    name = "on_osx_arm64",
    constraint_values = [
        "@platforms//os:osx",
        "@platforms//cpu:arm64",
    ],
)
